package cursojava.jpahibernate.orm.modelobanco.servicios;

public enum CodigoError {
	
	NINGUNO,
	CTA_ORIGEN_NO_EXISTE,
	CTA_DESTINO_NO_EXISTE,
	SALDO_INSUFICIENTE_EN_CUENTA_ORIGEN,
	ERROR_EN_TRANSFERENCIA, 
	COMPRAS_CLIENTE_NO_EXISTE,
	COMPRAS_ARTICULO_NO_EXISTE,
	COMPRAS_ARTICULO_CANTIDAD_INSUFICIENTE,
	COMPRAS_ERROR_EN_COMPRA

}
